version: "3.9"
services:
  # Proxy reverso
  nginx:
    image: nginx:latest
    container_name: reverse_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      proxy_net:
        ipv4_address: 10.10.10.2
    depends_on:
      - app1
      - app2
      - app3

  # Aplicação 1
  app1:
    image: php:8.1-apache
    container_name: app1
    volumes:
      - ./app1:/var/www/html
    networks:
      app1_net:
        ipv4_address: 10.10.10.18

  # Aplicação 2
  app2:
    image: php:8.1-apache
    container_name: app2
    volumes:
      - ./app2:/var/www/html
    networks:
      app2_net:
        ipv4_address: 10.10.10.34

  # Aplicação 3
  app3:
    image: php:8.1-apache
    container_name: app3
    volumes:
      - ./app3:/var/www/html
    networks:
      app3_net:
        ipv4_address: 10.10.10.50

  # Banco de Dados 1
  db1:
    image: mysql:8.0
    container_name: db1
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: app1db
    networks:
      db1_net:
        ipv4_address: 10.10.10.66
      backup_net1:
        ipv4_address: 10.10.10.113

  # Banco de Dados 2
  db2:
    image: mysql:8.0
    container_name: db2
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: app2db
    networks:
      db2_net:
        ipv4_address: 10.10.10.82
      backup_net2:
        ipv4_address: 10.10.10.129

  # Banco de Dados 3
  db3:
    image: mysql:8.0
    container_name: db3
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: app3db
    networks:
      db3_net:
        ipv4_address: 10.10.10.98
      backup_net3:
        ipv4_address: 10.10.10.145

  # PhpMyAdmin 1
  phpmyadmin1:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin1
    environment:
      PMA_HOST: db1
    ports:
      - "8081:80"
    networks:
      db1_net:
        ipv4_address: 10.10.10.68

  # PhpMyAdmin 2
  phpmyadmin2:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin2
    environment:
      PMA_HOST: db2
    ports:
      - "8082:80"
    networks:
      db2_net:
        ipv4_address: 10.10.10.84

  # PhpMyAdmin 3
  phpmyadmin3:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin3
    environment:
      PMA_HOST: db3
    ports:
      - "8083:80"
    networks:
      db3_net:
        ipv4_address: 10.10.10.100

  # Contêineres de Avaliação
  eval_proxy:
    image: jadilsonpaiva/full
    container_name: eval_proxy
    networks:
      proxy_net:
        ipv4_address: 10.10.10.1

  eval_app1:
    image: jadilsonpaiva/full
    container_name: eval_app1
    networks:
      app1_net:
        ipv4_address: 10.10.10.17

  eval_app2:
    image: jadilsonpaiva/full
    container_name: eval_app2
    networks:
      app2_net:
        ipv4_address: 10.10.10.33

  eval_app3:
    image: jadilsonpaiva/full
    container_name: eval_app3
    networks:
      app3_net:
        ipv4_address: 10.10.10.49

  eval_db1:
    image: jadilsonpaiva/full
    container_name: eval_db1
    networks:
      db1_net:
        ipv4_address: 10.10.10.65

  eval_db2:
    image: jadilsonpaiva/full
    container_name: eval_db2
    networks:
      db2_net:
        ipv4_address: 10.10.10.81

  eval_db3:
    image: jadilsonpaiva/full
    container_name: eval_db3
    networks:
      db3_net:
        ipv4_address: 10.10.10.97

  eval_backup1:
    image: jadilsonpaiva/full
    container_name: eval_backup1
    networks:
      backup_net1:
        ipv4_address: 10.10.10.114

  eval_backup2:
    image: jadilsonpaiva/full
    container_name: eval_backup2
    networks:
      backup_net2:
        ipv4_address: 10.10.10.130

  eval_backup3:
    image: jadilsonpaiva/full
    container_name: eval_backup3
    networks:
      backup_net3:
        ipv4_address: 10.10.10.146

networks:
  proxy_net:
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.0/28
  app1_net:
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.16/28
  app2_net:
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.32/28
  app3_net:
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.48/28
  db1_net:
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.64/28
  db2_net:
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.80/28
  db3_net:
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.96/28
  backup_net1:
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.112/28
  backup_net2:
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.128/28
  backup_net3:
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.144/28