version: '3.9'

networks:
  proxy_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.0/28
  app1_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.16/28
  app2_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.32/28
  app3_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.48/28
  db1_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.64/28
  db2_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.80/28
  db3_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.96/28
  backup_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.112/28

services:
  # Proxy reverso
  nginx:
    image: nginx:latest
    container_name: reverse_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - proxy_net
    depends_on:
      - app1
      - app2
      - app3

  # Aplicação 1
  app1:
    image: php:8.1-apache
    container_name: app1
    volumes:
      - ./app1:/var/www/html
    networks:
      - app1_net

  # Aplicação 2
  app2:
    image: php:8.1-apache
    container_name: app2
    volumes:
      - ./app2:/var/www/html
    networks:
      - app2_net

  # Aplicação 3
  app3:
    image: php:8.1-apache
    container_name: app3
    volumes:
      - ./app3:/var/www/html
    networks:
      - app3_net

  # Banco de dados 1
  db1:
    image: mysql:8.0
    container_name: db1
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: app1db
    networks:
      - db1_net
      - backup_net

  # Banco de dados 2
  db2:
    image: mysql:8.0
    container_name: db2
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: app2db
    networks:
      - db2_net
      - backup_net

  # Banco de dados 3
  db3:
    image: mysql:8.0
    container_name: db3
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: app3db
    networks:
      - db3_net
      - backup_net

  # Containers de avaliação
  jadilson_full_proxy:
    image: jadilsonpaiva/full
    container_name: jadilson_proxy
    networks:
      - proxy_net

  jadilson_full_app1:
    image: jadilsonpaiva/full
    container_name: jadilson_app1
    networks:
      - app1_net

  jadilson_full_app2:
    image: jadilsonpaiva/full
    container_name: jadilson_app2
    networks:
      - app2_net

  jadilson_full_app3:
    image: jadilsonpaiva/full
    container_name: jadilson_app3
    networks:
      - app3_net

  jadilson_full_backup:
    image: jadilsonpaiva/full
    container_name: jadilson_backup
    networks:
      - backup_net
